# Generated by Django 3.1.4 on 2020-12-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cathumanrelationship_human'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathumanrelationship',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
