# Generated by Django 3.1.4 on 2020-12-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_cathumanrelationship_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='related_cats',
            field=models.ManyToManyField(related_name='related_humans', through='cats.CatHumanRelationship', to='cats.Cat'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toys', to='cats.cat'),
        ),
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['name'], name='cats_cat_name_49f83f_idx'),
        ),
    ]
