# Generated by Django 3.1.4 on 2021-01-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20201230_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
