# Generated by Django 3.1.4 on 2021-02-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_cat_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'permissions': [('say_hello_cat', 'Say hello to the cat')]},
        ),
    ]
